services:
  db:
    container_name: crypto-app-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
  backend:
    container_name: crypto-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      - db
    ports:
      - "8081:8080"
  frontend:
    container_name: crypto-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
    - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge

volumes:
  pg_data: