server:
  port: 8080
spring:
  application:
    name: crypto-app
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: none
cryptoapp:
  environment: ${APP_ENV:development}
  jwt:
    expiration-ms: 259200000 # 3 days
    secret: ${JWT_SECRET}
    issuer: crypto-app
  mail-queue-url: ${MAIL_QUEUE_URL}
  service-email: ${SERVICE_EMAIL}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
coingecko:
  api-key: ${COIN_GECKO_API_KEY}
  api-url: ${COIN_GECKO_API_URL:https://api.coingecko.com/api/v3}